packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  electron: true
  electron-builder: true
  esbuild: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - sharp
  - unrs-resolver
  - electron
  - electron-builder
  - esbuild
